apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${parameters.name}
nameSuffix: ${parameters.name}

commonLabels:
  app: ${parameters.name}

images:
  - name: CHANGE_ME
    newName: ${trigger['image']}
    newTag: ${trigger['tag']}

resources:
- nginx-dex.yml
