apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dep-
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    spec:
      containers:
      - name: nginx
        image: CHANGE_ME 
        ports:
        - containerPort: 80
      volumes:
      - name: data-volume
        emptyDir: {}
